services:
  db:
    image: postgis/postgis:16-3.5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: letscycle
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d letscycle']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  dbdata:
